### PR TITLE
Added Automatic logo using clearbit API and removed js file in static (unneccessary)

### PR DESCRIPTION
**Pull request by chelsi-001011**

### CODE REVIEW

**Comment by sksingh1202** [comment]
Does the img tag which you have added replace the previous company's logo img tag?

**Comment by chelsi-001011** [comment]
Saket for adding an automatic logo, I have used clearbit API it is just a link which takes in company name...we do not require the company.logo anymore

**Comment by chelsi-001011** [comment]
so should I remove the company.logo one?

**Comment by sksingh1202** [comment]
> so should I remove the company.logo one?

Actually I have resolved that one, you can just check once and let me know whether what I have done is correct!

**Comment by sksingh1202** [comment]
you can try resolving the second one! And I'll review that!

**Comment by chelsi-001011** [comment]
Saket i can't see where u have resolved the image tag. In my resolve conflicts section it is still showing not resolved

**Comment by sksingh1202** [comment]
Check this one out!

**Review by chelsi-001011 — COMMENTED** [review]
Yes this works well...default picture when company logo doesn't exist

**Review by sksingh1202 — APPROVED** [review]

**Pull request merged**
